In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("titanic.csv")
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [4]:
print(df.shape)      # how many rows and columns?
print(df.columns)    # what columns exist?
print(df.dtypes)     # what data type is each column?
print(df.describe()) # statistics on all number columns

(891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [5]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
# Fix all three
df["Age"] = df["Age"].fillna(df["Age"].mean())
df = df.drop("Cabin", axis=1)
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Check missing values again
print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## My Data Exploration Checklist
1. Load — pd.read_csv()
2. Preview — df.head()
3. Size — df.shape
4. Columns — df.columns
5. Types — df.dtypes
6. Missing — df.isnull().sum()

In [7]:
print(df.shape)
print(df.head())

(891, 11)
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Embarked
0      0         A/5 21171   7.2500        S
1      0          PC 17599  71.2833        C
2      0  STON/O2. 3101282   7.9250        S
3      0            113803  53.1000        S
4      0            373450   8.0500        S

In [8]:
print(df["Survived"].value_counts())
print(df["Survived"].mean() * 100)

Survived
0    549
1    342
Name: count, dtype: int64
38.38383838383838

In [9]:
print(df["Age"].mean())

29.69911764705882

In [10]:
print(df["Fare"].mean())

32.204207968574636

In [11]:
df[df["Sex"] == "female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708,C
...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.000000,0,1,230433,26.0000,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.000000,0,0,7552,10.5167,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,29.1250,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S

In [12]:
df[(df["Pclass"] == 1) & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.000000,0,0,113783,26.5500,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.000000,0,0,113788,35.5000,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,29.699118,1,0,PC 17569,146.5208,C
...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.000000,0,0,17466,25.9292,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.000000,1,1,11751,52.5542,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.000000,0,1,11767,83.1583,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C

In [13]:
df.groupby("Sex")["Survived"].mean() * 100

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [48]:
result = df.groupby("Sex")["Survived"].mean() * 100
print(result.round(2))

Sex
female    74.20
male      18.89
Name: Survived, dtype: float64

EXERCISES FOR DAY 3

In [17]:
temps = np.array([28, 35, 22, 40, 18, 31])
print(f"{np.mean(temps):.2f} °C")  # average 
print(np.max(temps), '°C')     # highest
print(np.min(temps), '°C')     # lowest
print(np.std(temps), '°C')     # standard deviation

29.00 °C
40 °C
18 °C
7.438637868140466 °C

In [22]:
F= (9*temps/5)+32
for c, f in zip(temps, F):
    print(f"{c} °C → {f:.1f} °F")

28 °C → 82.4 °F
35 °C → 95.0 °F
22 °C → 71.6 °F
40 °C → 104.0 °F
18 °C → 64.4 °F
31 °C → 87.8 °F

In [23]:
print(temps[temps > 30])

[35 40 31]

State, Capital, Population(millions)
Lagos, Ikeja, 15
Kano, Kano, 13
Rivers, Port Harcourt, 7
Abuja, Abuja, 4
Oyo, Ibadan, 8

In [25]:
data = {
    "State": ["Lagos", "Kano", "Rivers", "Abuja", "Oyo"],
    "Capital":["Ikeja", "Kano", "Port Harcourt", "Abuja", "Ibadan"],
    "Population": [15000000, 13000000, 7000000, 4000000, 8000000]
}

df_Census = pd.DataFrame(data) 
print(df_Census)

    State        Capital  Population
0   Lagos          Ikeja    15000000
1    Kano           Kano    13000000
2  Rivers  Port Harcourt     7000000
3   Abuja          Abuja     4000000
4     Oyo         Ibadan     8000000

In [31]:
print(df_Census[["State", "Population"]])

    State  Population
0   Lagos    15000000
1    Kano    13000000
2  Rivers     7000000
3   Abuja     4000000
4     Oyo     8000000

In [32]:
print(df_Census[df_Census["Population"] > 7000000][["State", "Population"]])

   State  Population
0  Lagos    15000000
1   Kano    13000000
4    Oyo     8000000

In [34]:
print(df_Census[df_Census["Population"] > 7000000])

   State Capital  Population
0  Lagos   Ikeja    15000000
1   Kano    Kano    13000000
4    Oyo  Ibadan     8000000

In [36]:
print(df_Census["Population"].mean())

9400000.0

In [38]:
df_Census[df_Census["Population"] == df_Census["Population"].max()]

   State Capital  Population
0  Lagos   Ikeja    15000000